[2025-07-14T18:23:11.575+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: prepare_raw_data_daily.extract_one_day_to_unprocessed scheduled__2025-07-14T18:22:00+00:00 [queued]>
[2025-07-14T18:23:11.581+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: prepare_raw_data_daily.extract_one_day_to_unprocessed scheduled__2025-07-14T18:22:00+00:00 [queued]>
[2025-07-14T18:23:11.582+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-07-14T18:23:11.596+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): extract_one_day_to_unprocessed> on 2025-07-14 18:22:00+00:00
[2025-07-14T18:23:11.600+0000] {standard_task_runner.py:60} INFO - Started process 187 to run task
[2025-07-14T18:23:11.602+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'prepare_raw_data_daily', 'extract_one_day_to_unprocessed', 'scheduled__2025-07-14T18:22:00+00:00', '--job-id', '80', '--raw', '--subdir', 'DAGS_FOLDER/extract_daily_to_s3.py', '--cfg-path', '/tmp/tmpazqabn2t']
[2025-07-14T18:23:11.606+0000] {standard_task_runner.py:88} INFO - Job 80: Subtask extract_one_day_to_unprocessed
[2025-07-14T18:23:11.650+0000] {task_command.py:423} INFO - Running <TaskInstance: prepare_raw_data_daily.extract_one_day_to_unprocessed scheduled__2025-07-14T18:22:00+00:00 [running]> on host 2a36887fe580
[2025-07-14T18:23:11.712+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='prepare_raw_data_daily' AIRFLOW_CTX_TASK_ID='extract_one_day_to_unprocessed' AIRFLOW_CTX_EXECUTION_DATE='2025-07-14T18:22:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-14T18:22:00+00:00'
[2025-07-14T18:23:11.715+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/data_generator/extract_raw_to_s3_daily.py", line 69, in extract_one_day_to_unprocessed
    S3.head_bucket(Bucket=MINIO_UNPROCESSED)
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/client.py", line 553, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/client.py", line 946, in _make_api_call
    api_params = self._emit_api_params(
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/client.py", line 1072, in _emit_api_params
    self.meta.events.emit(
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/hooks.py", line 412, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/hooks.py", line 256, in emit
    return self._emit(event_name, kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/hooks.py", line 239, in _emit
    response = handler(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/handlers.py", line 282, in validate_bucket_name
    if not VALID_BUCKET.search(bucket) and not VALID_S3_ARN.search(bucket):
TypeError: expected string or bytes-like object
[2025-07-14T18:23:11.736+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=prepare_raw_data_daily, task_id=extract_one_day_to_unprocessed, execution_date=20250714T182200, start_date=20250714T182311, end_date=20250714T182311
[2025-07-14T18:23:11.746+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 80 for task extract_one_day_to_unprocessed (expected string or bytes-like object; 187)
[2025-07-14T18:23:11.779+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-07-14T18:23:11.792+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
